{% set version = "2.0.10" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-rbiom
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rbiom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rbiom/rbiom_{{ version }}.tar.gz
  sha256: aa86d2746eef5bb778b4928dca2bb36d79b0c9e814a86e5dcbd5eaf548f9da59

build:
  number: 0
  skip: True  # [win]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-ape                      # [build_platform != target_platform]
    - r-broom                    # [build_platform != target_platform]
    - r-cluster                  # [build_platform != target_platform]
    - r-dplyr                    # [build_platform != target_platform]
    - r-emmeans                  # [build_platform != target_platform]
    - r-fillpattern              # [build_platform != target_platform]
    - r-ggnewscale               # [build_platform != target_platform]
    - r-ggplot2                  # [build_platform != target_platform]
    - r-ggtext                   # [build_platform != target_platform]
    - r-jsonlite                 # [build_platform != target_platform]
    - r-magrittr                 # [build_platform != target_platform]
    - r-mgcv                     # [build_platform != target_platform]
    - r-openxlsx                 # [build_platform != target_platform]
    - r-parallelly               # [build_platform != target_platform]
    - r-pillar                   # [build_platform != target_platform]
    - r-plyr                     # [build_platform != target_platform]
    - r-r.utils                  # [build_platform != target_platform]
    - r-rjson                    # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-rcppparallel             # [build_platform != target_platform]
    - r-readr                    # [build_platform != target_platform]
    - r-readxl                   # [build_platform != target_platform]
    - r-slam                     # [build_platform != target_platform]
    - r-tidyplots                # [build_platform != target_platform]
    - r-vegan                    # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-ape
    - r-broom
    - r-cluster
    - r-dplyr
    - r-emmeans
    - r-fillpattern
    - r-ggnewscale
    - r-ggplot2
    - r-ggtext
    - r-jsonlite
    - r-magrittr
    - r-mgcv
    - r-openxlsx
    - r-parallelly
    - r-pillar
    - r-plyr
    - r-r.utils
    - r-rcpp
    - r-rcppparallel
    - r-readr
    - r-readxl
    - r-rjson
    - r-slam
    - r-tidyplots
    - r-vegan

  run:
    - r-base
    - r-ape
    - r-broom
    - r-cluster
    - r-dplyr
    - r-emmeans
    - r-fillpattern
    - r-ggnewscale
    - r-ggplot2
    - r-ggtext
    - r-jsonlite
    - r-magrittr
    - r-mgcv
    - r-openxlsx
    - r-parallelly
    - r-pillar
    - r-plyr
    - r-r.utils
    - r-rcpp
    - r-rcppparallel
    - r-readr
    - r-readxl
    - r-rjson
    - r-slam
    - r-tidyplots
    - r-vegan

test:
  commands:
    - $R -e "library('rbiom')"           # [not win]
    - "\"%R%\" -e \"library('rbiom')\""  # [win]

about:
  home: https://cmmr.github.io/rbiom/index.html

  license: AGPL-3.0-only
  license_family: AGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3

  summary: A toolkit for working with Biological Observation Matrix ('BIOM') files. Features include reading/writing all 'BIOM' formats, rarefaction, alpha diversity, beta diversity (including 'UniFrac'), summarizing counts by taxonomic level, and sample subsetting. Standalone functions for reading, writing, and subsetting
    phylogenetic trees are also provided. All CPU intensive operations are encoded in C with multi-thread support.

extra:
  recipe-maintainers:
    - conda-forge/r
    - dansmith01
